# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78077622bc50b82bf86b25797d19895de147826269b3b1f2fbe282959e9fbb129bf9de691ad2dc04f545d1dc07a99e9a153fe6288f0979be4a4ddf185a8fd274

test:
  secret_key_base: e5fd0591059bb6fc0cfab7cc4a786b04de8243debceb90532d0d9da15819c0fc5579b2202f6cf397162a0c0567cd8d71c13bb3f070fc56448a034dfb9ed37dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
